language: bash
services: docker

env:
  - VERSION=12.0 VARIANT=fpm
  - VERSION=12.0 VARIANT=apache
  - VERSION=11.0 VARIANT=fpm
  - VERSION=11.0 VARIANT=apache
  - VERSION=10.0 VARIANT=fpm
  - VERSION=10.0 VARIANT=apache

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - image="nextcloud:${VERSION}${VARIANT:+-$VARIANT}"
  - hash_before=$(git write-tree)

script:
  # Test Image
  - travis_retry docker build -t "$image" "${VERSION}/${VARIANT}"
  - ~/official-images/test/run.sh "$image"

  # Test generate-stackbrew-library.sh
  - ./generate-stackbrew-library.sh

  # Test update.sh
  - ./update.sh
  - bash -c "[[ $hash_before = $(git add -A && git write-tree) ]]"

after_script:
  - docker images
