contact_links:
    - name: ğŸ³ Docker Support and Help
      url: https://forums.docker.com/
      about: Configuration, installation, networking and other questions
    - name: â“ Nextcloud Support and Help
      url: https://help.nextcloud.com/
      about: Configuration, webserver/proxy or performance issues and other questions
